import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.45.4';

const allowedSet = (Deno.env.get('ALLOWED_ORIGINS') || 'https://iederees-create.github.io').split(',').map(v => v.trim());
const allowedOutcomes = ['fewer_missed_calls','easier_routing','remote_staff','usage_visibility','call_recording','keep_number'];
const allowed = {
  current_setup: ['not_sure','telkom_landline','on_premise_pbx','cloud_voip','mobile_only','other'],
  business_status: ['trading','new_business'], remote_required: ['not_sure','yes','no'], keep_number: ['not_sure','yes','no'],
  decision_timeline: ['researching','three_months','one_month','asap'], preferred_contact: ['email','whatsapp','conversation'],
};
const text = (value: unknown, max: number, required = true) => {
  if (typeof value !== 'string') { if (!required && (value === null || value === undefined)) return null; throw new Error('invalid_field'); }
  const clean = value.trim().replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g, '');
  if ((required && !clean) || clean.length > max) throw new Error('invalid_field'); return clean || null;
};
const enumValue = (payload: Record<string,unknown>, key: keyof typeof allowed) => { const value = text(payload[key], 50); if (!allowed[key].includes(value!)) throw new Error('invalid_field'); return value; };
export function validatePayload(input: unknown) {
  if (!input || typeof input !== 'object' || Array.isArray(input)) throw new Error('invalid_request'); const p = input as Record<string,unknown>;
  if (p.website) throw new Error('invalid_request');
  const staff = Number(p.staff_count), locations = Number(p.location_count);
  if (!Number.isInteger(staff) || staff < 1 || staff > 1000 || !Number.isInteger(locations) || locations < 1 || locations > 1000) throw new Error('invalid_field');
  if (!Array.isArray(p.outcomes) || p.outcomes.length > allowedOutcomes.length || p.outcomes.some(v => typeof v !== 'string' || !allowedOutcomes.includes(v))) throw new Error('invalid_field');
  const email = text(p.email,254)!; if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) throw new Error('invalid_field');
  return { contact_name:text(p.contact_name,120),company_name:text(p.company_name,160),role:text(p.role,100),email:email.toLowerCase(),whatsapp:text(p.whatsapp,40,false),staff_count:staff,location_count:locations,current_setup:enumValue(p,'current_setup'),business_status:enumValue(p,'business_status'),remote_required:enumValue(p,'remote_required'),keep_number:enumValue(p,'keep_number'),outcomes:[...new Set(p.outcomes)],problem_description:text(p.problem_description,1500),decision_timeline:enumValue(p,'decision_timeline'),preferred_contact:enumValue(p,'preferred_contact'),preferred_response_time:text(p.preferred_response_time,100),source_url:text(p.source_url,1000,false),utm_source:text(p.utm_source,150,false),utm_medium:text(p.utm_medium,150,false),utm_campaign:text(p.utm_campaign,150,false),utm_content:text(p.utm_content,150,false),utm_term:text(p.utm_term,150,false),referral_code:text(p.referral_code,100,false),privacy_version:text(p.privacy_version,50),turnstile_token:text(p.turnstile_token,2048,false)};
}
function cors(origin:string|null){const ok=origin&&allowedSet.includes(origin);return {'access-control-allow-origin':ok?origin!:'','access-control-allow-headers':'authorization,apikey,content-type','access-control-allow-methods':'POST,OPTIONS','vary':'Origin'}}
async function hashRateKey(ip:string){const secret=Deno.env.get('RATE_LIMIT_SECRET')||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(ip));return [...new Uint8Array(sig)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function verifyTurnstile(token:string|null,ip:string){const secret=Deno.env.get('TURNSTILE_SECRET_KEY');if(!secret)return true;if(!token)return false;const body=new FormData();body.set('secret',secret);body.set('response',token);body.set('remoteip',ip);const r=await fetch('https://challenges.cloudflare.com/turnstile/v0/siteverify',{method:'POST',body});const result=await r.json();return result.success===true}
async function notify(payload:Record<string,unknown>,submissionId:string){const key=Deno.env.get('RESEND_API_KEY'),from=Deno.env.get('RESEND_FROM_EMAIL'),to=Deno.env.get('ADMIN_NOTIFICATION_EMAIL');if(!key||!from||!to)return;const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{authorization:`Bearer ${key}`,'content-type':'application/json'},body:JSON.stringify({from,to:[to],subject:`New Exchange Line enquiry: ${payload.company_name}`,text:`A new inbound request was saved.\nSubmission: ${submissionId}\nCompany: ${payload.company_name}\nContact: ${payload.contact_name}\nTeam: ${payload.staff_count}\nPreferred contact: ${payload.preferred_contact}\n\nOpen the private dashboard for full details.`})});if(!r.ok)throw new Error('notification_failed')}
Deno.serve(async req=>{const origin=req.headers.get('origin'),headers={...cors(origin),'content-type':'application/json'};if(req.method==='OPTIONS')return new Response(null,{status:204,headers});if(req.method!=='POST'||!origin||!allowedSet.includes(origin))return new Response(JSON.stringify({error:'Request not allowed.'}),{status:403,headers});try{const payload=validatePayload(await req.json());const ip=req.headers.get('cf-connecting-ip')||req.headers.get('x-forwarded-for')?.split(',')[0].trim()||'unknown';if(!await verifyTurnstile(payload.turnstile_token,ip))return new Response(JSON.stringify({error:'Bot verification failed. Please try again.'}),{status:400,headers});const url=Deno.env.get('SUPABASE_URL'),serviceKey=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!url||!serviceKey)throw new Error('server_config');const supabase=createClient(url,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}}),rateKey=await hashRateKey(ip);const{data,error}=await supabase.rpc('submit_lead_transaction',{p_payload:payload,p_rate_key:rateKey});if(error){if(error.message.includes('rate_limited'))return new Response(JSON.stringify({error:'Too many attempts. Please wait and try again.'}),{status:429,headers});throw error}try{await notify(payload,String(data.submission_id))}catch(error){console.error('Internal notification failed after lead save',error)}return new Response(JSON.stringify({submission_id:data.submission_id,summary:data.summary}),{status:201,headers})}catch(error){console.error(error);return new Response(JSON.stringify({error:error instanceof Error&&error.message==='invalid_field'?'Please check the highlighted information and try again.':'We could not save this request. Please try again.'}),{status:400,headers})}});
